"""Property/metamorphic test for Gate WPI-3 — single-writer ingest assert (ADR 0110).

``P-SINGLE-WRITER-GAP``: at most one writer holds the SoR-spine promote
transaction at a time (``INV-SINGLE-WRITER``). Consequence: the committed
``StatementRecord.seq`` values the projector's incremental watermark reads form
a **contiguous, gap-free** consumption order.

* **Positive** — over synthetic single-writer batch schedules (each batch
  acquires the advisory lock, INSERTs, then commits — mirroring the exact
  placement ADR 0110 wires into ``resolve_pending``), the REAL projector
  (``worldmonitor.resolution.projector.project``) folds every committed ``seq``
  exactly once with no gap, and the final watermark equals the max committed
  ``seq``.

* **Metamorphic negative** — constructs the EXACT interleaving the advisory
  lock forbids: a lower ``seq`` committed AFTER the projector's watermark has
  already advanced past a higher ``seq`` (the classic seq-gap-under-concurrency
  hazard ADR 0100 D1 named and recorded as a revisit trigger). Because
  ``project(full_rebuild=False)`` reads only rows with ``seq > watermark``, the
  late-committed lower-``seq`` row is silently skipped forever — a real gap.
  This demonstrates the positive property is load-bearing: it depends on
  single-writer seq-assign/commit ordering, not luck.

Both tests are RED at collection time because the module-level import of
``acquire_spine_writer_lock`` / ``ConcurrentSpineWriterError`` from
``worldmonitor.resolution.spine_lock`` fails with ``ImportError`` — that module
does not exist until the builder creates it (the repo's gate-import idiom, see
the ``project`` import comment in ``tests/property/test_prop_fold_engine.py``).
"""

from __future__ import annotations

import uuid

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st
from sqlalchemy import select, text

from worldmonitor.db.engine import create_all, make_engine, session_factory
from worldmonitor.db.models import Base, ProjectionCheckpoint, StatementRecord
from worldmonitor.graph.neo4j_client import Neo4jClient
from worldmonitor.resolution.projector import project
from worldmonitor.resolution.spine_lock import (  # gate import: RED until builder lands it
    ConcurrentSpineWriterError,
    acquire_spine_writer_lock,
)

pytestmark = pytest.mark.integration

# A fixed advisory-lock key for this property (no collision with the integration
# test's key — each test uses its own database/session anyway, but the literal
# is kept distinct for clarity when reading logs).
_LOCK_KEY = 424243

# ---------------------------------------------------------------------------
# Hypothesis settings — container round-trips are slow; deadline=None required
# (mirrors tests/property/test_prop_fold_engine.py's ``_SETTINGS``).
# ---------------------------------------------------------------------------

_SETTINGS = settings(
    max_examples=15,
    deadline=None,
    # function_scoped_fixture: clean_graph/postgres_dsn are function-scoped but
    # each example explicitly resets both Postgres (_cleanup_postgres) and Neo4j
    # (execute_write DETACH DELETE) at the top of every example.
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.function_scoped_fixture],
)


def _cleanup_postgres(postgres_dsn: str) -> None:
    """Truncate ALL relational tables to isolate hypothesis examples (also resets
    the ``seq`` IDENTITY counters to 1 via ``RESTART IDENTITY``). Mirrors
    ``tests/property/test_prop_fold_engine.py::_cleanup_postgres``."""
    engine = make_engine(postgres_dsn)
    try:
        create_all(engine)
        with engine.begin() as conn:
            tables = ", ".join(t.name for t in Base.metadata.sorted_tables)
            conn.execute(text(f"TRUNCATE {tables} RESTART IDENTITY CASCADE"))
    finally:
        engine.dispose()


def _statement_row(
    *,
    canonical_id: str,
    value: str,
    dataset: str,
    seq: int | None = None,
) -> StatementRecord:
    """One well-formed StatementRecord for survivor ``canonical_id``. ``seq`` is
    normally left server-assigned (Postgres IDENTITY); an explicit ``seq``
    simulates a writer whose seq was ASSIGNED earlier but COMMITS later — the
    exact ADR-0100-D1 hazard the metamorphic negative reproduces (the ``seq``
    column is ``GENERATED BY DEFAULT AS IDENTITY``, so an app-supplied value is
    honoured verbatim, no ``OVERRIDING SYSTEM VALUE`` needed)."""
    kwargs: dict[str, object] = {
        "id": str(uuid.uuid4()),
        "statement_id": str(uuid.uuid4()),
        "canonical_id": canonical_id,
        "entity_id": f"{canonical_id}-member",
        "schema": "Company",
        "prop": "name",
        "value": value,
        "dataset": dataset,
        "reliability": "B",
        "retrieved_at": "2026-01-01T00:00:00Z",
    }
    if seq is not None:
        kwargs["seq"] = seq
    return StatementRecord(**kwargs)  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# Positive: synthetic single-writer batch schedule -> gap-free incremental fold
# ---------------------------------------------------------------------------


@st.composite
def _single_writer_schedule(draw: st.DrawFn) -> list[list[str]]:
    """Draw a synthetic single-writer batch schedule: 2..4 batches, each
    introducing 1..3 FRESH survivor ids (globally unique across the whole
    schedule via a monotonic counter — no merge/supersession machinery is
    needed to exercise the seq-gap property, just distinct per-batch writes)."""
    n_batches = draw(st.integers(min_value=2, max_value=4))
    schedule: list[list[str]] = []
    counter = 0
    for batch_index in range(n_batches):
        n_rows = draw(st.integers(min_value=1, max_value=3))
        batch: list[str] = []
        for _ in range(n_rows):
            batch.append(f"sw-gap-b{batch_index}-r{counter}")
            counter += 1
        schedule.append(batch)
    return schedule


@given(schedule=_single_writer_schedule())
@_SETTINGS
def test_p_single_writer_gap_positive(
    schedule: list[list[str]],
    postgres_dsn: str,
    clean_graph: Neo4jClient,
) -> None:
    """P-SINGLE-WRITER-GAP (positive): a single writer committing batch-by-batch
    — acquiring the advisory lock before each batch's INSERTs, exactly as ADR
    0110 wires it into ``resolve_pending`` — leaves a committed ``seq``
    sequence the REAL incremental projector consumes exactly once, with no
    gap, ending at watermark == max committed seq.
    """
    _cleanup_postgres(postgres_dsn)
    clean_graph.execute_write("MATCH (n) DETACH DELETE n")

    engine = make_engine(postgres_dsn)
    try:
        create_all(engine)
        sessions = session_factory(engine)

        committed_seqs: list[int] = []
        all_survivors: set[str] = set()
        total_statements_read = 0

        for batch in schedule:
            # --- One promote transaction: acquire lock -> INSERT -> commit ---
            # (ADR 0110 placement: "at the top of each batch iteration, before
            # any spine INSERT, inside the same transaction that the per-batch
            # session.commit() closes").
            with sessions() as session:
                acquire_spine_writer_lock(session, key=_LOCK_KEY)  # must never raise here
                for survivor in batch:
                    session.add(
                        _statement_row(
                            canonical_id=survivor,
                            value=f"{survivor}-val",
                            dataset="pswg-pos-ds",
                        )
                    )
                session.commit()

            with sessions() as session:
                batch_seqs = list(
                    session.execute(
                        select(StatementRecord.seq).where(StatementRecord.canonical_id.in_(batch))
                    ).scalars()
                )
            committed_seqs.extend(batch_seqs)
            all_survivors.update(batch)

            # --- The REAL incremental projector, driven after every batch ---
            with sessions() as session:
                result = project(session, clean_graph, full_rebuild=False)
            total_statements_read += result.statements_read

        assert committed_seqs, "test setup produced no committed statement rows"

        # Every committed seq consumed exactly once (no gap, no double-read).
        assert total_statements_read == len(committed_seqs), (
            "P-SINGLE-WRITER-GAP (positive) VIOLATED: the incremental projector read "
            f"{total_statements_read} statement row(s) across all batches, but "
            f"{len(committed_seqs)} were committed — every committed seq must be folded "
            "EXACTLY ONCE with no gap under single-writer discipline."
        )

        # Gap-free: sorted committed seqs form an unbroken run.
        expected = list(range(min(committed_seqs), max(committed_seqs) + 1))
        assert sorted(committed_seqs) == expected, (
            f"P-SINGLE-WRITER-GAP (positive) VIOLATED: committed seqs {sorted(committed_seqs)} "
            f"are not contiguous (expected {expected})."
        )

        # Final watermark == max committed seq.
        with sessions() as session:
            checkpoint = session.execute(select(ProjectionCheckpoint)).scalar_one()
        assert int(checkpoint.last_statement_seq) == max(committed_seqs), (
            f"P-SINGLE-WRITER-GAP (positive) VIOLATED: final watermark="
            f"{checkpoint.last_statement_seq} != max committed seq={max(committed_seqs)}."
        )

        # Every survivor materialised as exactly one node (nothing silently dropped).
        for survivor in all_survivors:
            rows = clean_graph.execute_read(
                "MATCH (n {id: $sid}) RETURN count(n) AS cnt", sid=survivor
            )
            count = int(rows[0]["cnt"]) if rows else 0
            assert count == 1, (
                f"P-SINGLE-WRITER-GAP (positive) VIOLATED: survivor={survivor!r} has "
                f"{count} node(s) in the projected graph, expected exactly 1."
            )

        # Sanity on the exception type the lock enforces (unused-import guard +
        # documents the contract this property depends on).
        assert issubclass(ConcurrentSpineWriterError, RuntimeError)
    finally:
        engine.dispose()


# ---------------------------------------------------------------------------
# Metamorphic negative: the exact interleaving the lock forbids DOES gap
# ---------------------------------------------------------------------------


@given(
    first_batch_size=st.integers(min_value=1, max_value=3),
    low_seq_offset=st.integers(min_value=0, max_value=2),
)
@_SETTINGS
def test_p_single_writer_gap_metamorphic_negative(
    first_batch_size: int,
    low_seq_offset: int,
    postgres_dsn: str,
    clean_graph: Neo4jClient,
) -> None:
    """P-SINGLE-WRITER-GAP (metamorphic negative): reproduce the EXACT
    interleaving ``INV-SINGLE-WRITER`` forbids — a lower ``seq`` COMMITS AFTER
    the projector's watermark has already advanced past a higher ``seq`` (the
    classic seq-assigned-earlier-but-committed-later race a second concurrent
    writer, unguarded by the advisory lock, could produce). The incremental
    fold — grounded in ``project(full_rebuild=False)`` reading only
    ``seq > watermark`` — must then SKIP the late-committed lower-seq row
    forever: a real gap. This is the load-bearing half of the property: the
    positive case's gap-free result depends on single-writer ordering, not on
    luck.
    """
    _cleanup_postgres(postgres_dsn)
    clean_graph.execute_write("MATCH (n) DETACH DELETE n")

    engine = make_engine(postgres_dsn)
    try:
        create_all(engine)
        sessions = session_factory(engine)

        # --- The "fast" writer: commits first, its seqs advance the watermark ---
        with sessions() as session:
            for i in range(first_batch_size):
                session.add(
                    _statement_row(
                        canonical_id="sw-gap-advance",
                        value=f"advance-val-{i}",
                        dataset="pswg-neg-ds",
                    )
                )
            session.commit()

        with sessions() as session:
            advanced_seqs = list(
                session.execute(
                    select(StatementRecord.seq).where(
                        StatementRecord.canonical_id == "sw-gap-advance"
                    )
                ).scalars()
            )
        max_advanced_seq = max(advanced_seqs)

        with sessions() as session:
            result_before = project(session, clean_graph, full_rebuild=False)
        assert result_before.statements_read == first_batch_size
        assert result_before.last_statement_seq == max_advanced_seq

        # --- The "slow" writer (forbidden by INV-SINGLE-WRITER): a DIFFERENT
        # survivor, but its row's seq was ASSIGNED before the fast writer's
        # (a value <= the watermark just advanced past), and it COMMITS after.
        # (StatementRecord.seq is GENERATED BY DEFAULT AS IDENTITY — an explicit
        # app-supplied value is honoured verbatim; this simulates the exact
        # commit-order-vs-assign-order inversion two concurrent writers would
        # produce, without needing real thread/connection concurrency.)
        victim_seq = max(1, max_advanced_seq - low_seq_offset)
        with sessions() as session:
            session.add(
                _statement_row(
                    canonical_id="sw-gap-victim",
                    value="victim-val",
                    dataset="pswg-neg-ds",
                    seq=victim_seq,
                )
            )
            session.commit()

        with sessions() as session:
            result_after = project(session, clean_graph, full_rebuild=False)

        # THE GAP: the watermark already passed victim_seq, so the late-
        # committed low-seq row is never read/folded — silent loss.
        assert result_after.statements_read == 0, (
            "P-SINGLE-WRITER-GAP (metamorphic negative) FAILED TO REPRODUCE: expected "
            f"0 rows read (victim seq={victim_seq} <= advanced watermark="
            f"{max_advanced_seq}), got {result_after.statements_read}."
        )
        victim_rows = clean_graph.execute_read(
            "MATCH (n {id: $sid}) RETURN count(n) AS cnt", sid="sw-gap-victim"
        )
        victim_count = int(victim_rows[0]["cnt"]) if victim_rows else 0
        assert victim_count == 0, (
            "P-SINGLE-WRITER-GAP (metamorphic negative) FAILED TO REPRODUCE: survivor "
            f"'sw-gap-victim' materialised {victim_count} node(s) despite seq="
            f"{victim_seq} <= the already-advanced watermark={max_advanced_seq} — the "
            "gap this property depends on did not occur."
        )
    finally:
        engine.dispose()
