"""projection outbox — monotonic seq columns + projection_checkpoint table (Gate 3a-i / ADR 0100)

Adds the three schema elements the fold engine (ADR 0100 D1) needs:

* ``seq BIGINT GENERATED BY DEFAULT AS IDENTITY`` on both ``statement`` and ``decision`` —
  the monotonic, server-assigned ordering column the projector checkpoints on (no separate
  outbox table; the log IS the outbox). NEVER set by application code; auto-assigned on every
  existing INSERT without touching the write path.

* ``projection_checkpoint`` — one row per projection target (e.g. ``"neo4j"``): stores the
  highest ``statement.seq`` / ``decision.seq`` folded so the projector can resume from a
  watermark (at-least-once ordering, ADR 0100 D1).

Purely additive — the direct write path (pipeline / statements / writer) is untouched; the
projector is DORMANT (no driver wiring, no compose profile) and never co-writes the live graph.

* ``upgrade()`` adds ``seq`` + index to ``statement``; same to ``decision``; creates
  ``projection_checkpoint``.
* ``downgrade()`` drops ``projection_checkpoint``; drops the two ``seq`` indexes + columns.

Do NOT edit 0001–0009 — migration history is immutable; the delta lives here only.
This migration head and the ``StatementRecord`` / ``DecisionRecord`` / ``ProjectionCheckpoint``
models in :mod:`worldmonitor.db.models` MUST agree byte-for-byte
(``tests/integration/test_migrations.py`` drift guard, ADR 0030).

Revision ID: 0010_projection_outbox
Revises: 0009_statement_spine
Create Date: 2026-07-04
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "0010_projection_outbox"
down_revision: str | None = "0009_statement_spine"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ------------------------------------------------------------------ statement.seq
    op.add_column(
        "statement",
        sa.Column("seq", sa.BigInteger(), sa.Identity(), nullable=False),
    )
    op.create_index("ix_statement_seq", "statement", ["seq"])

    # ------------------------------------------------------------------ decision.seq
    op.add_column(
        "decision",
        sa.Column("seq", sa.BigInteger(), sa.Identity(), nullable=False),
    )
    op.create_index("ix_decision_seq", "decision", ["seq"])

    # ------------------------------------------------------------------ projection_checkpoint
    op.create_table(
        "projection_checkpoint",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "last_statement_seq",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "last_decision_seq",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    # projection_checkpoint
    op.drop_table("projection_checkpoint")

    # decision.seq
    op.drop_index("ix_decision_seq", table_name="decision")
    op.drop_column("decision", "seq")

    # statement.seq
    op.drop_index("ix_statement_seq", table_name="statement")
    op.drop_column("statement", "seq")
